---
- name: Converge
  hosts: all
  become: true
  vars:
    change_password_require_hash: false
    change_password_allow_plaintext_password: true
    change_password_hash_salt_mode: hmac_inventory
    change_password_hmac_salt_secret: "molecule-test-secret-minimum-24-chars"
    change_password_accounts:
      - username: root
        password_plain: "Molecule-Test-Password-2026!"
        expire: false
        state: present
  roles:
    - role: ChgPassword
