---
- name: Converge
  hosts: all
  become: true
  vars:
    change_password_accounts:
      - username: root
        password_plain: "RootStrongPassword2026!"
        expire: false
      - username: testuser
        password_plain: "TestStrongPassword2026!"
        expire: false
    change_password_fail_if_user_missing: false
  tasks:
    - name: Ensure test user exists
      ansible.builtin.user:
        name: testuser
        state: present

    - name: Include role
      ansible.builtin.include_role:
        name: ChangePassword
