---
- name: Destroy Molecule containers
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_instance_name: chgpassword-ubuntu
    molecule_instance_config_path: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"

  tasks:
    - name: molecule | Remove test container
      community.docker.docker_container:
        name: "{{ molecule_instance_name }}"
        state: absent
        force_kill: true
      failed_when: false

    - name: molecule | Remove delegated instance configuration
      ansible.builtin.file:
        path: "{{ molecule_instance_config_path }}"
        state: absent
