---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: chgpassword-ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_DEPRECATION_WARNINGS: "False"
  config_options:
    defaults:
      roles_path: ../../..
      stdout_callback: default
      result_format: yaml
      bin_ansible_callbacks: true
      deprecation_warnings: false
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: ansible
