---
# Example inventory variables.
# Encrypt this file with ansible-vault before committing secrets.

change_password_accounts:
  - username: root
    password_hash: ""
    password_plain: ""
    expire: false
    state: present

change_password_default_hash_rounds: 656000
change_password_enforce_complexity: true
change_password_min_length: 14
change_password_fail_if_user_missing: true
change_password_lock_after_change: false
change_password_use_no_log: true
