---
- name: Prepare changepassword Molecule contract tests
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Prepare | Create temporary test directory
      ansible.builtin.file:
        path: /tmp/changepassword-molecule
        state: directory
        mode: "0755"
