---
- name: Verify negative Molecule scenario
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Verify | Negative scenario completed
      ansible.builtin.assert:
        that:
          - true
