---
- name: Converge all targets
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  check_mode: true

  vars:
    changepassword_use_no_log: false
    changepassword_audit_enabled: false
    changepassword_enable_audit_log: false
    changepassword_lock_enabled: false
    changepassword_enable_runtime_lock: false
    changepassword_check_shadow_backend: false
    changepassword_set_aging: false
    changepassword_require_etc_passwd_user: false
    changepassword_fail_if_same_hash: false
    changepassword_hmac_salt_secret: Molecule-Hmac-Secret-2026!
    changepassword_target_account: all
    changepassword_local_accounts:
      - username: root
        password: $6$rounds=656000$abcdefghijklmnop$01234567890123456789012345678901234567890123456789012345678901234567890123456789
        state: unlocked
        expire: false
      - username: moleculeops
        password: $6$rounds=656000$qbcdefghijklmnop$11234567890123456789012345678901234567890123456789012345678901234567890123456789
        state: unlocked
        expire: false
      - username: moleculeapp
        password: $6$rounds=656000$rbcdefghijklmnop$21234567890123456789012345678901234567890123456789012345678901234567890123456789
        state: unlocked
        expire: false

  roles:
    - role: changepassword
