---
- name: Create Molecule delegated Docker target
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Molecule | Create target container
      community.docker.docker_container:
        name: '{{ item.name }}'
        image: '{{ item.image }}'
        command: '{{ item.command | default(''/sbin/init'') }}'
        privileged: '{{ item.privileged | default(true) }}'
        pre_build_image: '{{ item.pre_build_image | default(true) }}'
        detach: true
        tty: true
        cgroupns_mode: host
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
        tmpfs:
          - /run
          - /tmp
        published_ports: '{{ item.published_ports | default([]) }}'
        env: '{{ item.env | default({}) }}'
        state: started
      loop: '{{ molecule_yml.platforms }}'
      loop_control:
        label: '{{ item.name }}'
    - name: Molecule | Build delegated instance configuration
      ansible.builtin.set_fact:
        molecule_instance_config_data: '{{ molecule_instance_config_data | default([]) + [{''instance'': item.name, ''address'':
          item.name, ''user'': ''root'', ''port'': 22, ''identity_file'': '''', ''connection'': ''community.docker.docker''}]
          }}'
      loop: '{{ molecule_yml.platforms }}'
      loop_control:
        label: '{{ item.name }}'
    - name: Molecule | Write delegated instance configuration
      ansible.builtin.copy:
        dest: '{{ molecule_instance_config }}'
        content: '{{ molecule_instance_config_data | to_nice_yaml }}'
        mode: '0600'
