---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: Chgpassword-ubuntu
    image: docker.io/ubuntu:22.04
  - name: Chgpassword-debian
    image: docker.io/debian:12
  - name: Chgpassword-rocky
    image: docker.io/rockylinux:9
  - name: Chgpassword-opensuse
    image: docker.io/opensuse/leap:15.6

provisioner:
  name: ansible
  env:
    ANSIBLE_DEPRECATION_WARNINGS: "False"
  config_options:
    defaults:
      deprecation_warnings: false
      stdout_callback: default
      result_format: yaml
      roles_path: ../../..

scenario:
  test_sequence:
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
