---
- name: Verify multi Molecule scenario
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Verify | Assert all selector contract
      ansible.builtin.assert:
        that:
          - changepassword_target_account in ['all', 'ALL', '*']
      vars:
        changepassword_target_account: all
