---
changepassword_hmac_salt_secret: ''
changepassword_local_accounts:
  - username: root
    password: replace-with-vault-secret-root-password
  - username: ansible
    password: replace-with-vault-secret-ansible-password
    state: unlocked
  - username: svc_backup
    password: $6$rounds=656000$replaceSaltHere$replaceSha512CryptHashHere
    state: locked
    expire: false
