---
- name: Change local UNIX account passwords
  hosts: all
  become: true
  gather_facts: true

  vars:
    changepassword_target_account: '{{ tgt_user | default(''root'') }}'
    changepassword_settings_dir: '{{ settings_dir | default(playbook_dir ~ ''/settings'') }}'
    changepassword_main_config_file: '{{ main_config_file | default(changepassword_settings_dir ~ ''/config.yml'') }}'
    changepassword_accounts_config_file: '{{ accounts_file | default(changepassword_settings_dir ~ ''/accounts.yml'') }}'

  pre_tasks:
    - name: Changepassword | Define configuration files
      ansible.builtin.set_fact:
        changepassword_config_files:
          - '{{ changepassword_main_config_file }}'
          - '{{ changepassword_accounts_config_file }}'
      delegate_to: localhost
      run_once: true
      become: false

    - name: Changepassword | Check configuration files exist
      ansible.builtin.stat:
        path: '{{ item }}'
      loop: '{{ changepassword_config_files }}'
      register: changepassword_config_files_stat
      delegate_to: localhost
      run_once: true
      become: false

    - name: Changepassword | Assert configuration files are valid
      ansible.builtin.assert:
        that:
          - item.stat.exists | default(false)
          - item.stat.isreg | default(false)
        fail_msg: 'Fichier de configuration introuvable ou invalide: {{ item.item }}'
        quiet: true
      loop: '{{ changepassword_config_files_stat.results | default([]) }}'
      delegate_to: localhost
      run_once: true
      become: false

    - name: Changepassword | Load configuration files
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop: "{{ changepassword_config_files }}"
      delegate_to: localhost
      run_once: true
      become: false

  roles:
    - role: changepassword
