---
changepassword_local_accounts: null
changepassword_target_account: root
changepassword_all_targets:
  - all
  - '*'
  - ALL
changepassword_require_hash: false
changepassword_allow_plaintext_password: true
changepassword_fail_if_user_missing: true
changepassword_allow_empty_password: false
changepassword_enforce_complexity: true
changepassword_min_length: 16
changepassword_require_upper: true
changepassword_require_lower: true
changepassword_require_digit: true
changepassword_require_special: true
changepassword_forbidden_plain_values:
  - password
  - Password123!
  - ChangeMe123!
  - Admin123!
changepassword_hash_algorithm: sha512
changepassword_default_hash_rounds: 656000
changepassword_min_hash_rounds: 500000
changepassword_hash_salt_mode: hmac_machine_id
changepassword_hash_salt_prefix: iriven_chgpasswd:v2
changepassword_hmac_algorithm: sha256
changepassword_hmac_salt_secret: ''
changepassword_default_hmac_salt_secret: jf?@#67568YPZs4Y6@5jG.7=pKw9jQ.j-d1ihlFpdGKsbuHru:?U?KeP573a
changepassword_require_custom_hmac_secret: true
changepassword_salt_length: 16
changepassword_set_aging: false
changepassword_min_days: null
changepassword_max_days: null
changepassword_warn_days: null
changepassword_inactive_days: null
changepassword_lock_after_change: false
changepassword_audit_logrotate_path: /etc/logrotate.d/iriven_chgpasswd
changepassword_audit_logrotate_frequency: daily
changepassword_audit_logrotate_rotate: 30
changepassword_audit_logrotate_compress: true
changepassword_audit_append_only: false
changepassword_audit_only: false
changepassword_machine_id_paths:
  - /etc/machine-id
  - /var/lib/dbus/machine-id
changepassword_forbidden_users:
  - bin
  - daemon
  - adm
  - lp
  - sync
  - shutdown
  - halt
  - mail
  - operator
  - games
  - ftp
  - nobody
  - nfsnobody
  - dbus
  - polkitd
  - sssd
  - systemd-network
  - systemd-resolve
  - systemd-timesync
  - systemd-coredump
  - rpc
  - rpcuser
changepassword_require_login_shell: true
changepassword_allowed_login_shells:
  - /bin/bash
  - /usr/bin/bash
  - /bin/sh
  - /usr/bin/sh
  - /bin/zsh
  - /usr/bin/zsh
  - /bin/ksh
  - /usr/bin/ksh
changepassword_require_etc_passwd_user: true
changepassword_fail_if_same_hash: false
changepassword_enable_audit_log: true
changepassword_enable_runtime_lock: true
changepassword_allow_default_hmac_fallback: false
